<template>
  <PageLayout>
    <article
      class="w-full mx-auto
        prose prose-lg lg:prose-xl
        py-16"
    >
      <img
        src="/about.svg"
        alt="Fav — Modern Favicon Generator"
        title="Fav — Modern Favicon Generator"
        class="mx-auto w-36 md:w-48 h-auto"
      >

      <section class="text-content text-opacity-70">
        <h2 class="font-bold text-content tracking-tight">
          What is Fav?
        </h2>

        <p>
          Fav is a next-generation icon generator for modern websites.
          Fav allows you to generate compact favicon set for modern browsers
          from a single source file, eliminating you from a hassle of
          manually generating multitudes different format of the said icon.
          Fav is directly inspired by <a
            class="link"
            href="https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs"
            target="_blank"
            rel="noopener"
            aria-label="EvilMartians Writeup"
          >
            this extensive writeup</a>
          written by <a
            class="link"
            href="https://evilmartians.com/"
            target="_blank"
            rel="noopener"
            aria-label="EvilMartians Website"
          >
            Evil Martians</a>.
        </p>

        <p>
          Fav executes all the required processing steps directly
          on your browser without any need to communicate with
          any backend server. Therefore, fav <strong>
            does not store any form of your personal data and usage.
          </strong>
        </p>

        <p>
          The favicons used on this site are self-generated by fav itself.
        </p>
      </section>

      <section class="text-content text-opacity-70">
        <h2 class="font-bold text-content tracking-tight">
          But, why another generator?
        </h2>

        <p>
          Good question! While there are multitudes of favicons generator
          out in the internet that you can already use today, they usually
          aren't updated for modern use cases.
        </p>

        <p>
          Back then, traditional browsers tend to have their own different
          formats and standards to manage favicons, which should be adhered
          to by responsible web developers. This situation is exacerbated by
          the rise of smartphones which — unsurprisingly — have different
          standards for managing favicons in mobile web browsers.
        </p>

        <p>
          However, browsers are maturing at blazing speed everyday;
          bringing more and more features on each updates,
          including better favicon support. This eliminates the need for storing
          20+ assets (which is generated by previous generators) on your
          hosting just for showing a tiny image on a browser tab.
        </p>
      </section>

      <section class="text-content text-opacity-70">
        <h2 class="font-bold text-content tracking-tight">
          Great! How do I use it then?
        </h2>

        <p>
          Just head to the <router-link
            class="link"
            to="/"
            aria-label="Fav Homepage"
          >
            homepage</router-link> and follow the instructions there.
          TL;DR, you'll have to perform the following steps:

          <ol class="list">
            <li>
              Upload an image as the base favicon. You can upload either
              <code>.png</code>, <code>.jpeg</code>, <code>.ico</code>,
              <code>.bmp</code>, <code>.webp</code>, or even <code>.svg</code>
              for the best result.
            </li>
            <li>
              Select favicon features support that you need.
              Fav will only generate favicon set that supports all
              of the selected features, without redundancy.
            </li>
            <li>
              Generate your favicon set by clicking the <code>Generate</code>
              button.
            </li>
          </ol>
        </p>

        <p>
          After your favicon set has been generated, your browser will initiate
          an <code>.zip</code> archive download.
          Don't worry, it's just Fav-generated favicons, totally safe!
        </p>

        <p>
          After the download process had finished, extract all contents of the
          archive into the <strong>public directory</strong> of
          your website and include the icons in your HTML entry point.
          For example:
        </p>

        <pre class="bg-gray-800 text-white overflow-x-auto">
&lt;!-- start: head tag --&gt;
  &lt;link rel="icon" href="/favicon.ico"&gt;
  &lt;link rel="icon" href="/icon.svg" type="image/svg+xml"&gt;
  &lt;link rel="apple-touch-icon" href="/apple-touch-icon.png"&gt;
  &lt;link rel="manifest" href="/manifest.webmanifest"&gt;
&lt;!-- end: head tag --&gt;
        </pre>
        <p>
          If you're still confused about which line(s) should you include,
          you can check the <strong>include HTML template</strong> checkbox
          and Fav will generate a starter HTML template for you.
        </p>
      </section>

      <section class="text-content text-opacity-70">
        <h2 class="font-bold text-content tracking-tight">
          Caveats
        </h2>

        <p>
          Fav is by no means perfect:
        </p>

        <ol class="list">
          <li>
            Since all process is done on your browser, the processing speed
            is 100% dependant on your hardware specification. But in general, it
            should be fast.
          </li>
        </ol>
      </section>

      <section class="text-content text-opacity-70">
        <h2 class="font-bold text-content tracking-tight">
          Contribution
        </h2>

        <p>
          Found a bug? Have some cool ideas?
          You can help improving Fav by visiting our
          <a
            href="https://github.com/Namchee/fav"
            class="link"
            rel="noopener"
            target="_blank"
            aria-label="Repository Link"
          >
            GitHub repository</a>.
          Any kind of contribution is welcome!
        </p>
      </section>
    </article>
  </PageLayout>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

import { useHead } from '@vueuse/head';

import PageLayout from '@/components/PageLayout.vue';

export default defineComponent({
  components: {
    PageLayout,
  },

  setup() {
    useHead({
      title: 'About Fav - Modern Favicon Generator',
      meta: [
        {
          name: 'description',
          content:
            'Fav is a next-generation favicon generator for modern websites.',
        },
        {
          name: 'og:title',
          content: 'About Fav - Modern Favicon Generator',
        },
        {
          name: 'og:description',
          content:
            'Fav is a next-generation favicon generator for modern websites.',
        },
        {
          name: 'og:url',
          content: 'https://fav.namchee.dev/about',
        },
        {
          name: 'twitter:description',
          content:
            'Fav is a next-generation favicon generator for modern websites.',
        },
      ],
    });
  },
});
</script>

<style lang="postcss" scoped>
.link {
  @apply transition-colors text-indigo-500 hover:text-indigo-700;
}

.list {
  list-style: none;
  counter-reset: list-number;

  & > li {
    position: relative;
    counter-increment: list-number;

    &::before {
      position: absolute;
      content: counter(list-number) ". ";
    }
  }
}
</style>
