name: Lint and test files

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v2.3.3
      - name: Setup NodeJS environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint code
        run: yarn lint
      - name: Run unit test
        run: yarn test:unit
